### ISSUE TITLE
Dronekit API not working Python 3

### ISSUE THREAD

**Issue by suneelbelkhale** [dronekit/dronekit-sitl#107]
Hi! I'm getting this error when I try to import connect from dronekit in the python shell. I tried downloading dronekit-sitl with both pip3 and pip2, and running the shell with python2 and python3.

<img width="802" alt="screen shot 2016-10-26 at 6 07 02 pm" src="https://cloud.githubusercontent.com/assets/6564198/19750580/1ce92c98-9ba7-11e6-9039-d39f35e1a3ae.png">

**Comment by pietrodn** [comment]
DroneKit now has full Python 3 support in the latest master. I think this can be closed.

**Comment by peterbarker** [comment]
Closed, thanks @pietrodn
