### ISSUE TITLE
Would be cool to have a way to point at a local build of flight code.  

### ISSUE THREAD

**Issue by eliao** [dronekit/dronekit-sitl#13]

**Comment by mrpollo** [comment]
you can potentially try this now by adding it here `/Users/rroche/.dronekit/sitl` with the following name convention:
```python
target = "copter"
version = "9.99"
"sitl-{}-v{}.tar.gz".format(target, version)
```
source: https://github.com/3drobotics/dronekit-sitl-runner/blob/master/dronekit_sitl_runner/__init__.py#L33

we should add an argument to enable this

**Comment by asetapen** [comment]
This would be really nice to have! Something like:

dronekit-sitl copter-3.3-rc5 ... (for remote)
dronekit-sitl --local ~/ArduPilot_Pro_Plus_Extra_Sparkes.px4 ... (for local)
