### ISSUE TITLE
How can I run Dronekit-SITL on systems with "ARM" processors?

### ISSUE THREAD

**Issue by developeralioz** [dronekit/dronekit-sitl#156]
I am using a MacBook with Apple M1 processor. I installed Ubuntu 20.04 ARM version on the virtual machine. I did all the installations correctly. But Dronekit-SITL is not working. I am sharing the error I got below.

<img width="921" alt="Ekran Resmi 2022-04-10 19 12 16" src="https://user-images.githubusercontent.com/71381857/162628844-5ce18410-fd5d-4cb4-80d1-e2b8969ed0a2.png">

How can I run Dronekit-SITL on ARM systems?
I read something called compiling from source in other issues. Can you help with this?

**Comment by hamishwillee** [comment]
Yes, you have to build the source since prebuilt binaries for ARM are not provided. There is some information on this https://dronekit-python.readthedocs.io/en/latest/develop/sitl_setup.html

There is a note there that explains how, after building, you can then run the binaries from SITL

> You can also use dronekit-sitl to start a SITL executable that you have built locally from source. To do this, put the file path of the target executable in the SITL_BINARY environment variable, or as the first argument when calling the tool.

**Comment by peterbarker** [comment]
On Sun, 10 Apr 2022, Hamish Willee wrote:

> Yes, you have to build the source since prebuilt binaries for ARM are not provided. There is some information on this https://dronekit-python.readthedocs.io/en/latest/develop/sitl_setup.html

Actually... we have for about three years :-)

https://firmware.ardupilot.org/Copter/beta/SITL_arm_linux_gnueabihf/

> There is a note there that explains how, after building, you can then run the binaries from SITL
>
>       You can also use dronekit-sitl to start a SITL executable that you have built locally from source. To do this, put the file path of the target executable in the SITL_BINARY environment variable, or as the first argument when calling the tool.

There's also a very experimental branch that can retrieve the binaries 
from the firmware server: 
https://github.com/peterbarker/dronekit-sitl/commits/wip/firmware-server

**Comment by hamishwillee** [comment]
Thanks for the clarification @peterbarker - I'll remember this for next time. You could update the docs.
