### ISSUE TITLE
Package default eeprom with builds

### ISSUE THREAD

**Issue by tcr3dr** [dronekit/dronekit-sitl#48]
Rather than have a parameter list, it is cheaper and more consistent to package a default eeprom file with the SITL runner.

**Comment by hamishwillee** [comment]
Really? As long as this allows you to have a different eeprom for every vehicle/build then sure.

**Comment by tcr3dr** [comment]
@hamishwillee Yeah. The alternative is very invasive, connecting then disconnecting to the created TCP port, leading to race conditions... no good!

**Comment by tcr3dr** [comment]
Working in https://github.com/dronekit/dronekit-sitl/pull/50

**Comment by hamishwillee** [comment]
Works for all builds? Ie separate/appropriate parameters/eeprom for copter vs plane and Rover and individual builds?

**Comment by hamishwillee** [comment]
Closing. Looking at the way the eeprom is created it doesn't appear to have any vehicle/platform dependency.
