### ISSUE TITLE
Not loading default params

### ISSUE THREAD

**Issue by squilter** [dronekit/dronekit-sitl#53]
I just followed the readme, and it didn't work.

`dronekit-sitl copter-3.3-rc5 -I0 -S --model quad --home=-35.363261,149.165230,584,353`

It would wipe the params, but not load the default ones.  So I couldn't arm because the RC wasn't calibrated.

**Comment by tcr3dr** [comment]
@squilter Try a clean install, then `dronekit-sitl copter-3.3`.

**Comment by tcr3dr** [comment]
@squilter (Also available on pip as dronekit-sitl==3.0.0)

**Comment by squilter** [comment]
I ran `sudo pip2 install dronekit-sitl --upgrade`
then
`dronekit-sitl copter-3.3`
and now I get
`Exception: SITL binary /home/squilter/.dronekit/sitl/copter-3.3/apm does not exist.`

**Comment by squilter** [comment]
can confirm that I now have `dronekit-sitl==3.0.0`

**Comment by tcr3dr** [comment]
Can you run `tree /home/squilter/.dronekit` for me? Did it mention the binary downloading or not?

**Comment by squilter** [comment]
It used to mention downloading binary.  Not anymore.

```
/home/squilter/.dronekit
└── sitl
    ├── copter-3.2.1
    │   ├── ArduCopter.elf
    │   ├── eeprom.bin
    │   └── logs
    ├── copter-3.3
    │   ├── ArduCopter.elf
    │   ├── logs
    │   └── terrain
    │       └── S36E149.DAT
    ├── copter-3.3-rc5
    │   ├── ArduCopter.elf
    │   ├── logs
    │   └── terrain
    │       └── S36E149.DAT
    └── sitl.tar.gz

9 directories, 7 files
```

**Comment by tcr3dr** [comment]
Ah. `setup.py` is now actually just blowing away the `~/.dronekit/sitl` directory on reinstall (since all the earlier binaries were pretty inconsistent, and the directory shouldn't store state). Feel free to do the same, or manually remove the copter-3.3 directory.

**Comment by tcr3dr** [comment]
I think I can handle this edge case automatically.

**Comment by squilter** [comment]
All is working now.  Thanks.

**Comment by tcr3dr** [comment]
@squilter Great. Can give this a try if you'd like. Probably will just republish with it. https://github.com/dronekit/dronekit-sitl/pull/55

**Comment by squilter** [comment]
Not sure how to downgrade with pip, so I don't know how to test it.

**Comment by tcr3dr** [comment]
Mmmm we'll just assume it works.

Software engineering.

**Comment by hamishwillee** [comment]
No wonder I feel like 50% of my job is QA .... :-)

**Comment by tcr3dr** [comment]
@hamishwillee Many Q, some A ;)
