### ISSUE TITLE
Use CI to actually test results

### ISSUE THREAD

**Issue by mrpollo** [dronekit/dronekit-sitl#6]
windows is still a thing, what can we do to support them?

**Comment by tcr3dr** [comment]
Presumably this works on Windows. But! CI should actually be used to test our builds!

**Comment by pietrodn** [comment]
#129 fixes CI builds.

**Comment by peterbarker** [comment]
@pietrodn Can this issue be closed?

**Comment by pietrodn** [comment]
Yes, since AppVeyor is running.
