### ISSUE TITLE
Clearly Define SITL acronym in the README.md

### ISSUE THREAD

**Issue by DanielHabib** [dronekit/dronekit-sitl#69]
As a new user of `dronekit`I am trying to make sense of my developer environment. That being said I believe `SITL` has something to do with the simulator, but I would like to know what the entire Acronym represents.

**Comment by hamishwillee** [comment]
Thanks @DanielHabib - good point. This will be fixed when #70 is merged.

**Comment by hamishwillee** [comment]
Now fixed on live site.
