### ISSUE TITLE
cant import the dronekit_sitl

### ISSUE THREAD

**Issue by keyurrakholiya** [dronekit/dronekit-sitl#94]
![screenshot 193](https://cloud.githubusercontent.com/assets/12994106/15891131/ccb26bb0-2d90-11e6-8b32-4626bf30a70b.png)

**Comment by hamishwillee** [comment]
You've miss-spelled the import: _ vs -

**Comment by keyurrakholiya** [comment]
nope, the problem was due to ASCII value of SPACE. i have copied the program 'hello drone' from the website. now i have written whole code again. this time, i am getting a different error.

AttributeError: 'module' object has no attribute 'start_default' #634

thank you for your help

**Comment by hamishwillee** [comment]
You will need to install the latest version of sitl from github to overcome that error - we need to do a new release and the version of PyPi isn't correct.
